use_default_settings: true

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en-AU"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "sophie-searxng-secret-key-2026"
  limiter: false
  image_proxy: false

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

enabled_default_engines:
  - name: google
  - name: duckduckgo
